[package]
name = "rustfun-rs"
version = "0.1.0"
authors = ["David Pollak <feeder.of.the.bears@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nginx-rs = { path = "../../nginx-rs" }

[profile.release]
debug = true
